DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS course_enrollments;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS departments;



CREATE TABLE students (
    student_id INTEGER PRIMARY KEY,
    name       VARCHAR(100),
    email      VARCHAR(150)
);
DROP TABLE students;

CREATE TABLE students (
    student_id INTEGER,
    name       VARCHAR(100),
    email      VARCHAR(150),
    PRIMARY KEY (student_id)
);
DROP TABLE students;


CREATE TABLE students (
    student_id INTEGER,
    name       VARCHAR(100),
    email      VARCHAR(150),
    CONSTRAINT pk_students PRIMARY KEY (student_id)
);
DROP TABLE students;


CREATE TABLE students (
    student_id INTEGER,
    name       VARCHAR(100),
    email      VARCHAR(150)
);
ALTER TABLE students ADD CONSTRAINT pk_students PRIMARY KEY (student_id);
DROP TABLE students;



CREATE TABLE students (
    student_id SERIAL PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(150) UNIQUE,
    faculty    VARCHAR(50)
);

INSERT INTO students (name, email, faculty) VALUES
    ('Alice Johnson', 'alice@alatoo.edu.kg', 'Computer Science'),
    ('Bob Smith',     'bob@alatoo.edu.kg',   'Mathematics'),
    ('Carol Davis',   'carol@alatoo.edu.kg', 'Computer Science');


SELECT * FROM students;



CREATE TABLE course_enrollments (
    student_id      INTEGER,
    course_id       INTEGER,
    semester        VARCHAR(20),
    enrollment_date DATE DEFAULT CURRENT_DATE,
    grade           CHAR(2),
    PRIMARY KEY (student_id, course_id, semester)
);

INSERT INTO course_enrollments (student_id, course_id, semester, grade) VALUES
    (1, 101, '2024-Spring', 'A'),
    (1, 102, '2024-Spring', 'B+'),
    (2, 101, '2024-Spring', 'A-'),
    (1, 101, '2024-Fall',   'A+');  

SELECT * FROM course_enrollments;



CREATE TABLE products (
    product_id   SERIAL PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price        DECIMAL(10,2)
);
INSERT INTO products (product_name, price) VALUES
    ('Notebook', 120.00),
    ('Pen',       25.50);
SELECT * FROM products;


CREATE TABLE transactions (
    transaction_id   BIGSERIAL PRIMARY KEY,
    amount           DECIMAL(15,2),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO transactions (amount) VALUES (1500.00), (320.75);
SELECT * FROM transactions;


CREATE TABLE orders (
    order_id      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    order_date    DATE DEFAULT CURRENT_DATE
);
INSERT INTO orders (customer_name) VALUES ('Alice Johnson'), ('Bob Smith');
SELECT * FROM orders;


CREATE TABLE customers (
    customer_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    email         VARCHAR(150)
);
INSERT INTO customers (customer_name, email)
VALUES ('Regular Customer', 'regular@example.com');        
INSERT INTO customers (customer_id, customer_name, email)
VALUES (1000, 'VIP Customer', 'vip@example.com');             
SELECT * FROM customers;


CREATE TABLE departments (
    dept_id   INTEGER PRIMARY KEY,
    dept_name VARCHAR(100)
);
INSERT INTO departments VALUES (1, 'Computer Science');
SELECT * FROM departments;


SELECT tablename, indexname, indexdef
FROM pg_indexes
WHERE tablename IN ('students', 'course_enrollments', 'products',
                    'transactions', 'orders', 'customers', 'departments')
ORDER BY tablename, indexname;


INSERT INTO departments VALUES (1, 'Mathematics');



INSERT INTO departments VALUES (NULL, 'Physics');


INSERT INTO course_enrollments (student_id, course_id, semester, grade)
VALUES (1, 101, '2024-Spring', 'C');


INSERT INTO orders (order_id, customer_name) VALUES (500, 'Carol Davis');


ALTER TABLE students ADD PRIMARY KEY (email);


SELECT * FROM departments;